### ISSUE TITLE
Building on Mavericks with Homebrew

### ISSUE THREAD

**Issue by colindean** [alperakcan/fuse-ext2#11]
I installed [osxfuse 2.8.0 from SF](http://sourceforge.net/projects/osxfuse/files/osxfuse-2.8.0/), not through Homebrew, because I thought something might be wrong with v2.7.6 that Homebrew has. Keep that in mind below. 

Probably could replace `/usr/local/include/osxfuse` with `$(brew --prefix osxfuse)/include` if you installed osxfuse from Homebrew.

```
brew install e2fsprogs m4 automake autoconf libtool
CFLAGS="-idirafter/$(brew --prefix e2fsprogs)/include -idirafter/usr/local/include/osxfuse" LDFLAGS="-L$(brew --prefix e2fsprogs)/lib" ./configure
make 
sudo make install
```

I got an error here about a missing directory.

```
sudo mkdir -p /usr/local/lib/umview/modules
sudo make install
```

Then I tried to mount it, but nothing happened when I did:

```
fuse-ext2 -v /dev/disk2s2 /Volumes/pi -o debug
```

**Comment by philippeBron** [comment]
Same problem here.

**Comment by alperakcan** [comment]
$ mkdir /Volumes/pi
$ sudo fuse-ext2 /dev/disk2s2 /Volumes/pi -o ro

pi volume icon should appear on your desktop.

**Comment by danpritts** [comment]
I bet the problem here was the "-v" option.  It prints the fuse version, and probably exits once it's done so.  You might consider adding some option checking to throw an error if anything else was provided with -v.

**Comment by lucamolteni** [comment]
Thanks @colindean with your variables I managed to build fuse-ext2 under Mavericks.
