### ISSUE TITLE
Install fuse-ext2 without Xcode

### ISSUE THREAD

**Issue by cheyao** [alperakcan/fuse-ext2#135]
Is it possible to install fuse-ext2 without Xcode? I have xcode-select installed, but I get this error while building:
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```
Or maby can someone give me a macos binary file (for intel cpu)?

**Comment by yurikoles** [comment]
Just replace `if DARWIN` with some random var check, e.g. `if I_HAVE_XCODE` in [tools/macosx/Makefile.am](https://github.com/alperakcan/fuse-ext2/blob/899f17c982dadcea13aa447c3a83c53b9431435a/tools/macosx/Makefile.am#L2)

**Comment by cheyao** [comment]
Deleting the contents of the file worked for me :) Thanks for the tip @yurikoles

**Comment by inferiorhumanorgans** [comment]
> `I_HAVE_XCODE`

To be clear this will cause the automake to fail, preventing this from building.  Even if it does work, the result will not include the preference pane.
