### ISSUE TITLE
Readability of README

### ISSUE THREAD

**Issue by franz-josef-kaiser** [alperakcan/fuse-ext2#19]
Currently it's really hardly readable. And there could be instructions for Homebrew as well as this makes it _much_ simpler.

**Comment by kadin2048** [comment]
Readability has been greatly improved but I'm still not sure what README.md line 51 is trying to say:
> OSXfuse io no need to install with MacFuse compatibility.   

I _think_ it's suggesting that OSXfuse no longer needs to be installed with the MacFuse compatibility layer option?  That seems like it'd be worth clarifying by someone who knows better than I do.
