### ISSUE TITLE
Need to run autogen.sh on OS X, but instruction doesn't mention this

### ISSUE THREAD

**Issue by mvmn** [alperakcan/fuse-ext2#22]
The instruction for OS X states:

> The easiest way is using Homebrew:
> 
> ```
> brew install e2fsprogs m4 automake autoconf libtool
> CFLAGS="-idirafter/$(brew --prefix e2fsprogs)/include -idirafter/usr/local/include/osxfuse" LDFLAGS="-L$(brew --prefix e2fsprogs)/lib" ./configure
> make 
> sudo make install
> ```

But there is no configure. autogen.sh must be run in order to generate it.
It's easy to figure out, but why not mention this in instruction?

**Comment by dgenin** [comment]
Just pulled 7b63f0aabac98a5b7dfeeabdda5ea1d5355077d6 and there is not autogen.sh or any other script for that matter. No Makefile either.

**Comment by mvmn** [comment]
https://github.com/alperakcan/fuse-ext2/blob/master/autogen.sh
?

**Comment by mvmn** [comment]
History shows it's there since 2008 BTW.

What does commit 7b63f0a has to do with this?

**Comment by dgenin** [comment]
Oops, my bad. Didn't notice I had descended an extra level. Thank you.

**Comment by mvmn** [comment]
You're welcome.
