### ISSUE TITLE
libtool-2.4.6.tar.gz has moved - link should be updated

### ISSUE THREAD

**Issue by wdwvt1** [alperakcan/fuse-ext2#25]
Executing `curl -O http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz` as mentioned in the `README.md` pulls down the following file:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://mirror.sdunix.com/gnu/libtool/libtool-2.4.6.tar.gz">here</a>.</p>
<hr>
<address>Apache/2.2.16 (Debian) Server at ftpmirror.gnu.org Port 80</address>
</body></html>
```

The installation proceeds if the referred link is used instead, specifically:
`curl -O http://mirrors.ocf.berkeley.edu/gnu/libtool/libtool-2.4.6.tar.gz`

**Comment by danieltroger** [comment]
> The installation proceeds if the referred link is used instead, specifically:
> `curl -O http://mirrors.ocf.berkeley.edu/gnu/libtool/libtool-2.4.6.tar.gz`

Note that you are being redirected to a mirror on a server physically close to you, which can vary from user to user, so I think instead of chosing a specific mirror it would be better to tell curl to follow the redirect, specifically by specifying the `-L` flag to curl, see my PR.

From the curl manpage:

```
-L/--location
              (HTTP/HTTPS) If the server reports that the requested page has moved to a different location (indicated with a Location: header and a 3XX response code), this option will make
              curl redo the request on the new place. (...)
```
