### ISSUE TITLE
Error with the command CFLAGS=..... No such file or directory

### ISSUE THREAD

**Issue by kormic** [alperakcan/fuse-ext2#27]
Hello there! After installing the packages using brew I run the command:
`CFLAGS="-idirafter/$(brew --prefix e2fsprogs)/include -idirafter/usr/local/include/osxfuse" LDFLAGS="-L$(brew --prefix e2fsprogs)/lib" ./configure
`
and I get 
`-bash: ./configure: No such file or directory`

Any help?

**Comment by louwers** [comment]
In what directory are you?
