### ISSUE TITLE
fails in autogen.sh

### ISSUE THREAD

**Issue by donggyukim** [alperakcan/fuse-ext2#32]
I fails in autogen.sh by getting the following:
Running autoreconf --verbose --install --force
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /opt/gnu/bin/autoconf --force
autoreconf: running: /opt/gnu/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:10: installing './compile'
configure.ac:4: installing './missing'
automake: warnings are treated as errors
/opt/gnu/share/automake-1.15/am/ltlibrary.am: warning: 'umfuseext2.la': linking libtool libraries using a non-POSIX
/opt/gnu/share/automake-1.15/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
fuse-ext2/Makefile.am:10:   while processing Libtool library 'umfuseext2.la'
fuse-ext2/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1
Removing autom4te.cache

**Comment by sa-wilson** [comment]
This can be fixed by adding `m4_ifdef([AM_PROG_AR], [AM_PROG_AR])` to the configure.ac file, however I'm now having issues getting it to find the ext2fs library from e2fsprogs as part of the configure stage, so I can't be sure if it actually works.

**Comment by zg** [comment]
I encountered the same issue.  Adding `m4_ifdef([AM_PROG_AR], [AM_PROG_AR])` to the `configure.ac` file fixed the issue.

**Comment by johannes87** [comment]
`autogen.sh` succeeds now, thanks. I added the line after the `m4_ifdef([AC_PROG_LIB],[AC_PROG_LIB],[m4_warn(portability,[Missing AC_PROJ_LIB])])` line.

**Comment by kadin2048** [comment]
Received the same error on 10.10.5 with all the latest dependencies installed via Homebrew (except for m4, which Homebrew choked on for some reason, so I'm using the OS-supplied M4 1.4.6).  Had to manually edit the `configure.ac` file as well, so this is still an issue.

**Comment by kenti-lan** [comment]
kadin2048 , i had the same issues.Could you tell me how need to do exactly?

**Comment by kenti-lan** [comment]
@kadin2048 i had the same issues.Could you tell me how need to do exactly?

**Comment by UnConundrum** [comment]
In the fuse-ext2 directory, you'll find a file named configure.ac.  Edit that file and add the line:

m4_ifdef([AM_PROG_AR], [AM_PROG_AR])

after the line that says:

m4_ifdef([AC_PROG_LIB],[AC_PROG_LIB],[m4_warn(portability,[Missing AC_PROJ_LIB])])

That is between lines 12 and 13 on my installation.  Save the edited file and run ./autogen.sh again.
