### ISSUE TITLE
Unable to mount my ext4 external drive with fuse-ext2

### ISSUE THREAD

**Issue by Battant** [alperakcan/fuse-ext2#38]
Hello,
problem :
seams a moment (probably since a update) my external heard drive could be mount by fuse-ext2

My configuration :

mac os 10.10.5
Fuse for osx 2.8,3

Whith fuse-ext2 0.0.7  I have this problem :

`fuse-ext2 /dev/disk1 /Volumes/Sav_linux/
fuse-ext2: version:'0.0.7', fuse_version:'27' [main (../../fuse-ext2/fuse-ext2.c:324)]
fuse-ext2: enter [do_probe (../../fuse-ext2/do_probe.c:30)]
fuse-ext2: Error while trying to open /dev/disk1 (rc=13) [do_probe (../../fuse-ext2/do_probe.c:34)]
fuse-ext2: Probe failed [main (../../fuse-ext2/fuse-ext2.c:340)]
`

the system don't try to mount the ext4 volume when i connet it

whith fuse-ext2 0.0.6  I have this problem :

the system try to mount the ext4 volume but show this error message

FUSE-EXT2 could not mount /dev/disk1s1
at /Volumes/Untitled because the following problem occurred:

`fuse-ext2: enter [do_probe (../../fuse-ext2/do_probe.c:30)]
fuse-ext2: Error while reading bitmaps (rc=2133571358) [do_probe (../../fuse-ext2/do_probe.c:39)]
fuse-ext2: Probe failed [main (../../fuse-ext2/fuse-ext2.c:337)]`

Could you help me please to fix thees issues ?

Thanks for your support

Best regards

Battant

**Comment by Battant** [comment]
Hello,

Now when I try to mount my ext4 external device on os 10.10.5, with ext-fuse-xt2 0.0.7, I get this error
sudo mount -t fuse-ext2 /dev/disk1 /Volumes/Sav_linux/
63:92: execution error: SystemUIServer got an error: AppleEvent timed out. (-1712)
An this alert message

FUSE-EXT2 could not mount /dev/disk1
at /Volumes/Sav_linux because the following problem occurred:

fuse-ext2: version:'0.0.7', fuse_version:'27' [main (../../fuse-ext2/fuse-ext2.c:324)]
fuse-ext2: enter [do_probe (../../fuse-ext2/do_probe.c:30)]
fuse-ext2: Error while trying to open /dev/disk1 (rc=13) [do_probe (../../fuse-ext2/do_probe.c:34)]
fuse-ext2: Probe failed [main (../../fuse-ext2/fuse-ext2.c:340)


Could you help me please to fix this issue

Best regards

Battant

**Comment by IlPum** [comment]
juljul-i:Volumes ilpumconsultingservice$ diskutil list
/dev/disk0
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *250.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS IlPum                   249.2 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
/dev/disk1
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            fuse-ext2-0.0.7        *1.0 MB     disk1

**Comment by srd424** [comment]
Did this get fixed? Just seen it trying to access an ext4 image .. using whatever ancient version is in Ubuntu (0.4-1.1ubuntu0.18.04.1) ..

**Comment by srd424** [comment]
Looking at it, do_probe tries to open the image with EXT2_FLAG_RW regardless of whether rw mode is requested?
