### ISSUE TITLE
Build fails at the very end.

### ISSUE THREAD

**Issue by caesarsamsi** [alperakcan/fuse-ext2#39]
The error message is:

Running autoreconf --verbose --install --force
autoreconf: 'configure.ac' or 'configure.in' is required
Removing autom4te.cache
./zip: line 13: ./configure: No such file or directory
make: **\* No targets specified and no makefile found.  Stop.
make: **\* No rule to make target `install'.  Stop.
MacPro:gnu caesarsamsi$ 

The other quick way also has an error at the end:

Disabling debug support by default
./configure: line 18435: syntax error near unexpected token `e2fs,ext2fs'
./configure: line 18435:`PKG_CHECK_MODULES(e2fs,ext2fs >= 1.41.13)'
make: **\* No targets specified and no makefile found.  Stop.
Password:
make: **\* No rule to make target `install'.  Stop.

There is no way to build on OSX Yosemite.

**Comment by juniorRubyist** [comment]
Have you cloned into the repository?

**Comment by alperakcan** [comment]
please read the readme.md for build instructions
