### ISSUE TITLE
Creating files in an EXT4 filesystem will not set EXT4_EXTENTS_FL flag

### ISSUE THREAD

**Issue by ngkaho1234** [alperakcan/fuse-ext2#5]
All the subsequent IO operations will not build extents tree in the corresponding inode, instead blockmap is used

**Comment by ngkaho1234** [comment]
This can be fixed by setting EXT4_EXTENTS_FL and initializing the i_block array with an extent tree header when creating inode.

**Comment by alperakcan** [comment]
thanks i will look as soon as possible. it would be very helpful if you can create a pull request.

**Comment by ngkaho1234** [comment]
okay.

**Comment by ngkaho1234** [comment]
RP was proposed. :-)

**Comment by alperakcan** [comment]
my bad, i havent much time to check. merged pull request. thank you for your effort and support :)
