### ISSUE TITLE
./autogen.sh "No such file or directory"

### ISSUE THREAD

**Issue by cephasiii** [alperakcan/fuse-ext2#55]
I followed the instructions to install fuse-ext2 on a mac line by line. All went well until I called the command ./autogen.sh. I was in the "gnu" directory, but the script wasn't there. Anyone know what I may be missing? I didn't recieve any errors at any point of the previous steps.

Thanks for your help.

**Comment by alperakcan** [comment]
./autogen.sh is under fuse-ext directory, i've updated the readme.
