### ISSUE TITLE
How can I check and repaire my ext4 partition with (fuse-ext2) (fsck) ?

### ISSUE THREAD

**Issue by Battant** [alperakcan/fuse-ext2#57]
Hello,

All is in the title

Tanks for your support

Best regards

Battant

**Comment by Battant** [comment]
Configuration :
mac os 10.11.6

**Comment by Battant** [comment]
I could'nt found e2fsck or fsck ext4

My configuration is now mac os 10.12.4

**Comment by alperakcan** [comment]
if you installed e2fsprogs as in readme, is it located at /opt/gnu/sbin, or /usr/local/sbin
