### ISSUE TITLE
Freezes when listing or changing into directory when volume has a bigger than 4kb block size

### ISSUE THREAD

**Issue by garegin16** [alperakcan/fuse-ext2#68]
Basically, this has been documented in various places
I tried it with Ubuntu 17.10, but people have been reporting this for a few years.
The bug report is here.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776248

**Comment by alperakcan** [comment]
hi,

the bug link you provided is not releated to the fuse-ext2.
anyway, i did followed the instructions and i can not reproduce with latest source code on github, can you?

$ cat /etc/debian_version
9.2
$ dpkg -s e2fslibs | grep Version
Version: 1.43.4-2
$ dpkg -s libfuse-dev | grep Version

alper.

**Comment by garegin16** [comment]
I didn’t try with the latest code. But many people have reported the same issue around 2014, 2015. You can’t cd or ls into the mounted directory. It just freezes. Will try when I get back to office

**Comment by garegin16** [comment]
Even if it works with the latest git code, is it possible you can check for version 0.4?
Because that’s the version that Ubuntu uses. I don’t even know when it was released because the latest release says 0.0.9 on your git.
https://launchpad.net/ubuntu/artful/+source/fuse-umfuse-ext2

**Comment by alperakcan** [comment]
fuse-ext2 has no relation with fuse-umfuse-ext2. you should talk to that project's maintainers. i can not update some other project.

**Comment by garegin16** [comment]
Sorry
Didn’t notice
And what do you know, umfuse’s page has the issue listed.
He never commented on it, even though it’s been three years.
