### ISSUE TITLE
Bug in $buid_dir/fuse-ext2/Makefile.am

### ISSUE THREAD

**Issue by billgertz** [alperakcan/fuse-ext2#7]
Hello,

Just a short note - there is a small bug in the make install path. Trying to install under OS X results in an error and then dies:
.
.
.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-data-hook
cd "//usr/local/lib/umview/modules" && rm -f 
/bin/sh: line 0: cd: //usr/local/lib/umview/modules: No such file or directory
make[3]: *** [install-data-hook] Error 1
make[2]: *** [install-data-am] Error 2
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

The fuse-ext2/Makefile.am declares a target 'install-data-hook:' that should only be productive for LINUX and not DARWIN. I've made a non-productive version for DARWIN to crudely patch around the problem for now:

   if DARWIN
   install-data-hook:
   endif

   if LINUX
   install-data-hook:
           cd "$(DESTDIR)/$(moddir)" && rm -f $(mod_LTLIBRARIES)
   endif

Why? If I am reading the make file correctly the declaration for mod_LTLIBRARIES is only productive for LINUX:

   if LINUX
   mod_LTLIBRARIES = umfuseext2.la
   endif

The same if clause could be done around the declaration for moddir but it's not completely necessary, but would make for a cleaner make file:

   if LINUX
   moddir =  $(libdir)/umview/modules
   endif

Hope this helps and thanks for all your hard work. I'll test and get back to you - if you have a test suite for OS X I'd be happy to run it.

Kind Regards,

Bill Gertz

**Comment by awesomebing1** [comment]
Took me a while to figure out how to apply this patch. I figured out it was towards the bottom of (source code)/fuse-ext2/Makefile.am, not (source code)/Makefile.am. Thank you for figuring this out!

**Comment by alperakcan** [comment]
thanks for the report and solution
