### ISSUE TITLE
Please tag a release for Homebrew

### ISSUE THREAD

**Issue by yalp** [alperakcan/fuse-ext2#71]
I am trying to submit a formula for Homebrew, could you please tag a release of the project to allow me to submit the formula ?

The Homebrew maintainers will only allow a submission related a stable release.
https://github.com/Homebrew/homebrew-core/pull/24302

**Comment by alperakcan** [comment]
just released v0.0.10 upon request.

https://github.com/alperakcan/fuse-ext2/releases/tag/v0.0.10
https://github.com/alperakcan/fuse-ext2/tree/v0.0.10

thank for your support!
