### ISSUE TITLE
dyld: Library not loaded: /usr/local/lib/libfuse.2.dylib

### ISSUE THREAD

**Issue by shrx** [alperakcan/fuse-ext2#9]
I installed fuse-ext2 binary 0.0.7 from sourceforge on OS X Yosemite 10.10.3.
When I run `fuse-ext2` in the terminal, I get an error:

```
$ fuse-ext2
dyld: Library not loaded: /usr/local/lib/libfuse.2.dylib
  Referenced from: /usr/local/bin/fuse-ext2
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by shrx** [comment]
Looks related: https://github.com/osxfuse/osxfuse/issues/114

**Comment by alperakcan** [comment]
0.0.7 is a very old release, may not work with yosemite.

**Comment by johnjelinek** [comment]
:+1: I'm getting this problem on Mavericks.
